#!/bin/bash
# Development script to run both backend and frontend

echo "═══════════════════════════════════════════════════════════════"
echo "   Resume Screening System - Development Mode"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Please run these commands in separate terminal windows:"
echo ""
echo "📌 Terminal 1 - Backend (FastAPI):"
echo "   make run-backend"
echo "   or"
echo "   uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "📌 Terminal 2 - Frontend (Streamlit):"
echo "   make run-frontend"
echo "   or"
echo "   streamlit run src/web/streamlit_app.py"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Alternatively, use Docker:"
echo "   docker-compose up"
echo ""
echo "═══════════════════════════════════════════════════════════════"
